### ISSUE TITLE
Version 0.3

### ISSUE THREAD

**Issue by sbrugman** [StefOe/indrnn-pytorch#4]
There is one single change to make `addition_test.py` work with PyTorch 0.3.XX, which is:
```
# For PyTorch 0.3.XX
losses.append(loss.data.cpu())
# For PyTorch 0.4.XX
losses.append(loss.data.cpu().item())
```

**Comment by StefOe** [comment]
I want to abandon PyTorch 0.3. as the current stable branch is 0.4 and in 0.5/1.0 this wont work.
